[package]
name = "heatmap"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
crossterm = { version = "0.27.0", default-features = false }
rusqlite = { version = "0.30.0", features = ["bundled"] }
thiserror = "1.0.50"
